import React from 'react'
import Pixel from './Pixel'


const App = () => {
  return (
    <div>
     
    
     
     
      
      <div className = 'pixel'>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      </div>
    
    
    
    
    
    </div>
 
   
  )
}

export default App
